/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a running app and kept here so
// typechecking has the expected project shape from the first commit.
