name = "rentease-api"
main = "src/index.ts"
compatibility_date = "2026-06-09"

[vars]
ALLOWED_ORIGINS = "https://rentease.milahly.top,http://localhost:3000,http://localhost:3001"
APP_URL = "https://rentease.milahly.top"
ENVIRONMENT = "demo"

[[routes]]
pattern = "api-rentease.milahly.top"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "rentease"
database_id = "46f27ac6-6d04-4a5e-a937-b1d579ca6a1a"
migrations_dir = "../../packages/db/migrations"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "rentease-assets"
